######################################################################
# Automatically generated by qmake (2.01a) ?? 2? 7 17:09:06 2017
######################################################################
QT  += webkit network
TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += mainwindow.h
FORMS += mainwindow.ui
SOURCES += main.cpp mainwindow.cpp
